server:
  port: 8080
  servlet:
    session:
      timeout: 30m

jwt:
  access-key: ${JWT_ACCESS_TOKEN}
  refresh-key: ${JWT_REFRESH_TOKEN}
  expiration-minutes: ${JWT_EXPIRATION_TIME_MINUTES}
  expiration-DAYS: ${JWT_EXPIRATION_TIME_DAYS}
  header: Authorization
  prefix: Bearer

application:
  domain-name: ${BASE_DOMAIN_NAME}
  domain-image: ${BASE_DOMAIN_IMAGE}
  domain-upload : ${BASE_UPLOAD_PATH}
  static-resources: ${STATIC_FOLDER}

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DBMS_CONNECTION}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MariaDBDialect

  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  ai:
    openai:
      api-key: ${OPENAI_GEMINI_KEY}
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.0-flash

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    org:
      springframework:
        web:
          socket=DEBUG:
        messaging=DEBUG: